#pragma once

namespace Ion
{
	// Camera.h
	struct RCameraRenderProxy;
	class Camera;
	// Drawable.h
	class IDrawable;
	// IndexBuffer.h
	class IndexBuffer;
	// Light.h
	struct RLightRenderProxy;
	struct LightUniforms;
	class Light;
	class DirectionalLight;
	// Material.h
	class Material;
	// Mesh.h
	struct MeshUniforms;
	class Mesh;
	// Renderer.h
	struct RRendererData;
	struct ScreenTextureRenderData;
	struct REditorPassPrimitive;
	struct EditorPassData;
	class Renderer;
	// RendererCore.h
	struct ViewportDescription;
	// Scene.h
	struct SceneUniforms;
	struct RPrimitiveRenderProxy;
	class Scene;
	// Shader.h
	struct ShaderInfo;
	class Shader;
	// Texture.h
	struct TextureDimensions;
	struct TextureDescription;
	class Texture;
	// UniformBuffer.h
	struct UniformData;
	class UniformBuffer;
	// VertexAttribute.h
	struct VertexAttribute;
	// VertexBuffer.h
	class VertexBuffer;
	// VertexLayout.h
	class VertexLayout;
}
