#pragma once

#include "Core/StringParser.h"
#include "Core/Error/Error.h"
#include "Logger.h"

namespace Ion
{
	template<>
	struct TEnumParser<ELogLevel>
	{
		ENUM_PARSER_TO_STRING_BEGIN(ELogLevel)
		ENUM_PARSER_TO_STRING_HELPER(Trace)
		ENUM_PARSER_TO_STRING_HELPER(Debug)
		ENUM_PARSER_TO_STRING_HELPER(Info)
		ENUM_PARSER_TO_STRING_HELPER(Warn)
		ENUM_PARSER_TO_STRING_HELPER(Error)
		ENUM_PARSER_TO_STRING_HELPER(Critical)
		ENUM_PARSER_TO_STRING_END()

		ENUM_PARSER_FROM_STRING_BEGIN(ELogLevel)
		ENUM_PARSER_FROM_STRING_HELPER(Trace)
		ENUM_PARSER_FROM_STRING_HELPER(Debug)
		ENUM_PARSER_FROM_STRING_HELPER(Info)
		ENUM_PARSER_FROM_STRING_HELPER(Warn)
		ENUM_PARSER_FROM_STRING_HELPER(Error)
		ENUM_PARSER_FROM_STRING_HELPER(Critical)
		ENUM_PARSER_FROM_STRING_END()
	};
}
